name: Install Test
on:
  push:
    branches:
      - main
      - vNext
  pull_request:

jobs:
  install_matrix:
    name: Install Matrix Test
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        OctoPrintVersion:
          - 1.5.0
          - 1.6.0
          - 1.7.0
          - 1.8.0
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Test Install
        run: |
          pip install OctoPrint==${{ matrix.OctoPrintVersion }}
          pip install -e .
          octoprint serve --iknowwhatimdoing -c tests/fixtures/config.yaml &

      - name: Run cypress (experimental)
        continue-on-error: true
        uses: cypress-io/github-action@v4
        with:
          record: true
          browser: chrome
          spec: cypress/e2e/octoprint/headerAnnouncements.cy.js
          working-directory: tests
          wait-on: "http://localhost:5000/login/"
          wait-on-timeout: 30
          config: defaultCommandTimeout=10000,requestTimeout=10000
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          # Recommended: pass the GitHub token lets this action correctly
          # determine the unique run id necessary to re-run the checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
